### ISSUE TITLE
♻️ 유저 도메인 리팩토링

### ISSUE THREAD

**Issue by jjikky** [Murakano/murakano-be#89]
### ♻️ 진행할 작업 설명

```markdown
유저 도메인에 대해 전체적인 리팩토링  진행
불필요하거나 적합하지 않은 로직에 대해 1차 개선 진행
공통 로직 메서드 추출
레이어간 책임 명확히 분리
```

### ☘️TODO

-  [x] 유저 컨트롤러 비동기 예외처리 유틸함수 적용
-  [x] 인증 관련 로직 리팩토링
-  [x] passport 유저 조회 키 값 변경
-  [x] 유저 서비스, 리포지토리 로직 전체 개선
