### ISSUE TITLE
♻️ 비동기 예외처리 유틸함수 추가

### ISSUE THREAD

**Issue by jjikky** [Murakano/murakano-be#91]
### ♻️ 진행할 작업 설명

```markdown
반복되는 try-catch 구문 제거를 위해 유틸함수 추가
```

### ☘️TODO

-   [x] catchAsync 유틸 함수 추가
-   [x] word 도메인에 적용
-   [ ] user 도메인에 적용
