### ISSUE TITLE
♻️ 단어 조회 성능 개선

### ISSUE THREAD

**Issue by jjikky** [Murakano/murakano-be#99]
### ♻️ 진행할 작업 설명

```markdown
단어조회 관련 쿼리 실행 계획 분석 및 인덱스 최적화
Redis Lazy 캐싱 및 크론잡활용 write-back 동기화로 인기검색어 조회 성능 개선
```

### ☘️TODO

-   [x] word 필드 인덱스 설정
-   [x] 인기검색어 조회 Lazy 캐싱 적용
-   [x] 조회수 동기화 크론잡 추가
